# Generated by Django 6.0.1 on 2026-01-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PengelolaWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('organisasi', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('ketua', 'Ketua'), ('editor', 'Editor')], max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengelola/')),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='blog.galerikategori')),
            ],
        ),
        migrations.CreateModel(
            name='PersonilBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(choices=[('ketua', 'Ketua Bidang'), ('sekretaris', 'Sekretaris Bidang'), ('anggota', 'Anggota')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personil/')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bidang')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('capaian', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prestasi/')),
                ('tingkat', models.CharField(choices=[('lokal', 'Lokal'), ('daerah', 'Daerah'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=30)),
                ('tahun', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bidang')),
            ],
            options={
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(upload_to='program/')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bidang')),
            ],
        ),
    ]
