# Generated by Django 6.0.1 on 2026-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PimpinanUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jabatan', models.CharField(default='Ketua Umum', max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pimpinan/')),
                ('periode', models.CharField(max_length=50)),
                ('sambutan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
