# Generated by Django 6.0.1 on 2026-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pimpinanumum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimpinanumum',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='pimpinanumum',
            name='sambutan',
        ),
        migrations.AlterField(
            model_name='pimpinanumum',
            name='jabatan',
            field=models.CharField(max_length=150),
        ),
    ]
