# Generated by Django 6.0.1 on 2026-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_pimpinanumum_periode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidang',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bidang/'),
        ),
    ]
