# Generated by Django 6.0.1 on 2026-03-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bidang_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personilbidang',
            options={},
        ),
        migrations.AlterField(
            model_name='personilbidang',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personil', to='blog.bidang'),
        ),
        migrations.AlterField(
            model_name='personilbidang',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personil_bidang/'),
        ),
        migrations.AlterField(
            model_name='programkerja',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='blog.bidang'),
        ),
        migrations.AlterField(
            model_name='programkerja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='program_kerja/'),
        ),
        migrations.AlterField(
            model_name='programkerja',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
