# Generated by Django 6.0.1 on 2026-01-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonilBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='personil/')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bidang')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(upload_to='program/')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bidang')),
            ],
        ),
    ]
