# Generated by Django 6.0.1 on 2026-01-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bidang_personilbidang_programkerja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'verbose_name': 'Bidang', 'verbose_name_plural': 'Bidang'},
        ),
        migrations.AlterModelOptions(
            name='personilbidang',
            options={'verbose_name': 'Personil Bidang', 'verbose_name_plural': 'Personil Bidang'},
        ),
        migrations.AlterModelOptions(
            name='programkerja',
            options={'verbose_name': 'Program Kerja', 'verbose_name_plural': 'Program Kerja'},
        ),
    ]
