# Generated by Django 6.0.1 on 2026-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_bidang_options_alter_personilbidang_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pengurus',
                'verbose_name_plural': 'Pengurus',
                'ordering': ['urutan'],
            },
        ),
        migrations.AlterModelOptions(
            name='personilbidang',
            options={'ordering': ['urutan'], 'verbose_name': 'Personil Bidang', 'verbose_name_plural': 'Personil Bidang'},
        ),
    ]
