# Generated by Django 6.0.1 on 2026-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pengurus_alter_personilbidang_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personilbidang',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personil/'),
        ),
        migrations.AlterField(
            model_name='personilbidang',
            name='jabatan',
            field=models.CharField(choices=[('ketua', 'Ketua Bidang'), ('sekretaris', 'Sekretaris Bidang'), ('anggota', 'Anggota')], max_length=20),
        ),
    ]
