# Generated by Django 6.0.1 on 2026-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_personilbidang_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={},
        ),
        migrations.AddField(
            model_name='bidang',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
    ]
