# Generated by Django 6.0.1 on 2026-01-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_bidang_options_bidang_deskripsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengurus',
            options={'ordering': ['urutan']},
        ),
        migrations.AlterModelOptions(
            name='personilbidang',
            options={'ordering': ['urutan']},
        ),
        migrations.AlterModelOptions(
            name='programkerja',
            options={},
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('capaian', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('lokal', 'Lokal'), ('daerah', 'Daerah'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], max_length=30)),
                ('tahun', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bidang')),
            ],
            options={
                'ordering': ['-tahun'],
            },
        ),
    ]
