# Generated by Django 6.0.1 on 2026-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_pengurus_options_alter_personilbidang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='prestasi/'),
        ),
    ]
