# Generated by Django 6.0.1 on 2026-01-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_galerikategori_galeri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galerikategori',
            options={},
        ),
        migrations.RemoveField(
            model_name='galerikategori',
            name='slug',
        ),
        migrations.AlterField(
            model_name='galeri',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='blog.galerikategori'),
        ),
    ]
